# -*- coding: utf-8 -*-
"""Avaliação Python - João Victor Barboza Rodrigues.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cD7I5FV8qZ1kAVflizVOnShQBQggvvhh

Data: 18/02/2022
Aluno: João Victor Barboza Rodrigues

1) Um palíndromo é uma palavra ou frase que pode ser lida no seu sentido normal, da esquerda para a direita, bem como no sentido contrário, da direita para a esquerda, sem que haja mudança nas palavras que a formam e no seu significado.
Exemplos: 
a ) amor a roma          b) o lobo ama o bolo    c) socorram-me subi no onibus em marrocos

Crie um algoritmo em Python que leia um string e diga se ela é ou não é um palíndromo
"""

# Usuário insere a palvra e o sistema retira espaços e hífens:

palavra = input("Digite uma palavra ou frase: ")
palavra = palavra.replace(" ","")
palavra = palavra.replace("-","")

# Algoritmo:

tam = 0
for i in range(len(palavra)):
  if palavra[len(palavra) - len(palavra) + i] == palavra[len(palavra) - len(palavra) - 1 - i]:
    tam += 1
    if tam == len(palavra):
      print("A palavra ou frase é um palíndromo")
  else:
    print("A palavra ou frase não é um palíndromo")
    break

"""2) Crie um algoritmo em python que leia um número inteiro N, positivo e mostre na tela a soma dos números de 1 até N.     ( 1 + 2 + 3 + 4 ……. + N)

Ex: N = 5      -     Deverá mostrar na tela (15)             -     1 + 2 + 3 + 4 + 5 = 15
Ex: N = 7      -     Deverá mostrar na tela (28)             -     1 + 2 + 3 + 4 + 5 + 6 + 7 = 28

"""

# Validação do número N:

while True:
  try:
    N = int(input("Digite um número inteiro positivo: "))
    if N > 0:
      break
    else:
      print("Resposta inválida. Digite um número inteiro e positivo: ")
  except:
    print("Resposta inválida. Digite um número inteiro e positivo: ")

# Algoritmo:

print(f'({N}) - ', end = "")
soma = 0
for i in range(N):
  soma += i + 1
  if i == N - 1:
    print(i + 1, end=" ")
  else:
    print(i + 1,end=" + ")

print("=", soma)

"""3) Crie um algoritmo em python que leia um número inteiro positivo N e preencha uma lista com os N primeiros números da sequência abaixo. O primeiro número da sequência é o 2.

2      3        5        9        17        33        65     129       257 …………
"""

# Validação do número N:

while True:
  try:
    N = int(input("Digite um número inteiro positivo: "))
    if N > 0:
      break
    else:
      print("Resposta inválida. Digite um número inteiro e positivo: ")
  except:
    print("Resposta inválida. Digite um número inteiro e positivo: ")

# Algoritmo:

inicial = 2

print(inicial, end = " ")

for i in range(N - 1):
  inicial += inicial - 1
  print(inicial, end = " ")

print(".....")

"""4) Faça um algoritmo que leia e armazene em um dicionário informações sobre nome, idade, altura, peso, cpf, rg,  endereço e telefone de uma pessoa. Todos esses dados deverão ser enviados via usuário. Ao final, percorra o dicionário já criado e exiba as informações que nele estão preenchidas. Não esqueça de fazer as validações quanto a valores inteiros e reais."""

dic = {}

dic['nome'] = input(f'Digite o nome da pessoa: ')

while True:
  try:
    dic['idade'] = int(input(f'Digite o idade da pessoa: '))
    if dic['idade'] > 0:
      break
    else:
      print("Resposta inválida. Digite um número inteiro e positivo: ")
  except:
    print("Resposta inválida. Digite um número inteiro e positivo: ")

while True:
  try:
    dic['altura'] = float(input(f'Digite o altura da pessoa: '))
    if dic['altura'] > 0:
      break
    else:
      print("Resposta inválida. Digite um número positivo: ")
  except:
    print("Resposta inválida. Digite um número positivo: ")

while True:
  try:
    dic['peso'] = float(input(f'Digite o peso da pessoa: '))
    if dic['peso'] > 0:
      break
    else:
      print("Resposta inválida. Digite um número positivo: ")
  except:
    print("Resposta inválida. Digite um número positivo: ")


dic['cpf'] = input(f'Digite o cpf da pessoa: ')
dic['rg'] = input(f'Digite o rg da pessoa: ')
dic['endereço'] = input(f'Digite o endereço da pessoa: ')
dic['telefone'] = input(f'Digite o telefone da pessoa: ')

print(dic)

"""5) Crie um programa que leia o valor de um salário em reais e calcule o valor do INSS (de acordo com a faixa salarial), , FGTS e Imposto de Renda(Se aplicável) e ao final informe o salário bruto, o valor de cada uma das retenções e o salário líquido do funcionário. Você deverá usar funções para encontrar os valores de FGTS e INSS. O restante fica ao seu critério

INSS - 
12% (Até R$2400,00)
15% (Acima de R$2400,00)

FGTS - 8%
"""

# Validação do salário digitado:

while True:
  try:
    salario = float(input("Digite o salário: "))
    if salario > 0:
      break
    else:
      print("Resposta inválida. Digite um número positivo: ")
  except:
    print("Resposta inválida. Digite um número positivo: ")

# Algoritmo:

def inss_fgts(salario):
  if salario < 2400:
    inss = 0.12 * salario
  else:
    inss = 0.15 * salario
  fgts = 0.08 * salario
  liquido = salario - inss - fgts
  return f'''
  Salário bruto: R$ {salario:.2f}
  INSS - R$ {inss:.2f}
  FGTS - R$ {fgts:.2f}
  Salário líquido: R$ {liquido:.2f}'''

print(inss_fgts(salario))